<?xml version="1.0" encoding="utf-8"?><Database Name="EmployeeDB" Class="EmployeeDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmpSal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="EmpJob" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmpDeptNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>